version: 1.0.1.{build}
configuration: Release

branches:
  only:
    - master

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal

after_build:
  - ps: Get-ChildItem -Recurse C:\Users\appveyor\AppData\Local\Temp\*\JE*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -Verbosity Normal -DeploymentName JEPackages }

skip_tags: false

deploy:
- provider: NuGet
  api_key:
    secure: DgZLtZcCWRTg+CP/Cj8wZpBNjNWDsP2lxsEmz615tXu7UQvXyIH7WyBLXSQ/CwH6
  artifact: JEPackages
  on:
    APPVEYOR_REPO_TAG: true

on_finish:
  -ps: >- 
      foreach ($artifactName in $artifacts.keys) {
        Write-Host $artifacts[$artifactName].name
        Write-Host $artifacts[$artifactName].type
        Write-Host $artifacts[$artifactName].path
      }