version: 1.0.1.{build}
configuration: Release

branches:
  only:
    - master

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:
- provider: NuGet
  api_key:
    secure: DgZLtZcCWRTg+CP/Cj8wZpBNjNWDsP2lxsEmz615tXu7UQvXyIH7WyBLXSQ/CwH6
  artifact: '**\JE*.nupkg'
  on:
    APPVEYOR_REPO_TAG: true