version: 1.0.1.{build}
configuration: Release

branches:
  only:
    - master

assembly_info:
  patch: true
  file: '**\*AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal

after_build:
  - ps: dir
  - ps: Get-ChildItem C:\Users\appveyor\AppData\Local\Temp\*\JE*.nupkg -Recurse | % { Copy-Item -Destination C:\projects\je-identityserver-security }
  - ps: dir

skip_tags: false

artifacts:
- path: '**\JE.*.nupkg'
  name: JEPackages

deploy:
- provider: NuGet
  api_key:
    secure: DgZLtZcCWRTg+CP/Cj8wZpBNjNWDsP2lxsEmz615tXu7UQvXyIH7WyBLXSQ/CwH6
  artifact: JEPackages
  on:
    APPVEYOR_REPO_TAG: true